

# cardset = Cardset.new(name: "デフォルトセット１", user_id: 1)

# cardset.words.new(name:"come", meaning:"来る")
# cardset.words.new(name:"walk", meaning:"歩く")
# cardset.words.new(name:"run", meaning:"走る")
# cardset.words.new(name:"speak", meaning:"話す")
# cardset.words.new(name:"say", meaning:"言う")
# cardset.words.new(name:"talk", meaning:"話す")
# cardset.words.new(name:"help", meaning:"助ける")
# cardset.words.new(name:"have", meaning:"持っている")
# cardset.words.new(name:"bring", meaning:"持ってくる")
# cardset.words.new(name:"take", meaning:"持っていく")
# cardset.words.new(name:"like", meaning:"好む")
# cardset.words.new(name:"love", meaning:"愛する")
# cardset.words.new(name:"call", meaning:"呼ぶ")
# cardset.words.new(name:"succeed", meaning:"成功する")
# cardset.words.new(name:"fail", meaning:"失敗する")
# cardset.words.new(name:"lent", meaning:"貸す")
# cardset.words.new(name:"check", meaning:"確認する")
# cardset.words.new(name:"enter", meaning:"入る")
# cardset.words.new(name:"fly", meaning:"飛ぶ")
# cardset.words.new(name:"vanish", meaning:"消える")

# cardset.save


cardset_test1 = Cardset.new(name: "学校の英単語", user_id: 1, use: 2)

cardset_test1.words.new(name:"school", meaning:"学校")
cardset_test1.words.new(name:"classroom", meaning:"教室")
cardset_test1.words.new(name:"pencil", meaning:"鉛筆")
cardset_test1.words.new(name:"mechanical pencil", meaning:"シャープペン")
cardset_test1.words.new(name:"pen", meaning:"ペン")
cardset_test1.words.new(name:"desk", meaning:"机")
cardset_test1.words.new(name:"bag", meaning:"カバン")
cardset_test1.words.new(name:"notebook", meaning:"ノート")
cardset_test1.words.new(name:"homework", meaning:"宿題")
cardset_test1.words.new(name:"diary", meaning:"日記")
cardset_test1.words.new(name:"window", meaning:"窓")
cardset_test1.words.new(name:"book", meaning:"本")
cardset_test1.words.new(name:"dictionary", meaning:"辞書")
cardset_test1.words.new(name:"chair", meaning:"椅子")
cardset_test1.words.new(name:"door", meaning:"ドア")
cardset_test1.words.new(name:"piano", meaning:"ピアノ")
cardset_test1.words.new(name:"guitar", meaning:"ギター")
cardset_test1.words.new(name:"subject", meaning:"教科")
cardset_test1.words.new(name:"English", meaning:"英語")
cardset_test1.words.new(name:"math", meaning:"算数")
cardset_test1.words.new(name:"science", meaning:"理科")
cardset_test1.words.new(name:"music", meaning:"音楽")
cardset_test1.words.new(name:"art", meaning:"芸術")
cardset_test1.words.new(name:"social study", meaning:"社会")
cardset_test1.words.new(name:"study", meaning:"勉強する")
cardset_test1.words.new(name:"student", meaning:"生徒")
cardset_test1.words.new(name:"teach", meaning:"教える")
cardset_test1.words.new(name:"teacher", meaning:"先生")
cardset_test1.words.new(name:"eraser", meaning:"消しゴム")


cardset_test1.save


cardset_test2 = Cardset.new(name: "家の中", user_id: 1, use: 2)

cardset_test2.words.new(name:"kitchen", meaning:"来る")
cardset_test2.words.new(name:"room", meaning:"部屋")
cardset_test2.words.new(name:"glass", meaning:"ガラス")
cardset_test2.words.new(name:"floor", meaning:"床")
cardset_test2.words.new(name:"ceiling", meaning:"天井")
cardset_test2.words.new(name:"table", meaning:"テーブル")
cardset_test2.words.new(name:"picture", meaning:"写真、絵")
cardset_test2.words.new(name:"pot", meaning:"鍋")
cardset_test2.words.new(name:"spoon", meaning:"スプーン")
cardset_test2.words.new(name:"plate", meaning:"皿")
cardset_test2.words.new(name:"knife", meaning:"ナイフ")
cardset_test2.words.new(name:"stairs", meaning:"階段")
cardset_test2.words.new(name:"restroom", meaning:"トイレ")
cardset_test2.words.new(name:"bed", meaning:"ベッド")
cardset_test2.words.new(name:"pillow", meaning:"枕")
cardset_test2.words.new(name:"blanket", meaning:"ブランケット")
cardset_test2.words.new(name:"television", meaning:"テレビ")
cardset_test2.words.new(name:"air conditioner", meaning:"エアコン")
cardset_test2.words.new(name:"bath", meaning:"お風呂")
cardset_test2.words.new(name:"bathroom", meaning:"お風呂場, トイレ")
cardset_test2.words.new(name:"towel", meaning:"タオル")
cardset_test2.words.new(name:"clothes", meaning:"服")
cardset_test2.words.new(name:"closet", meaning:"クローゼット")
cardset_test2.words.new(name:"shelf", meaning:"棚")
cardset_test2.words.new(name:"chopsticks", meaning:"箸")

cardset_test2.save

cardset_test3 = Cardset.new(name: "体", user_id: 1, use: 2)

cardset_test3.words.new(name:"body", meaning:"体")
cardset_test3.words.new(name:"eye", meaning:"目")
cardset_test3.words.new(name:"ear", meaning:"耳")
cardset_test3.words.new(name:"head", meaning:"頭")
cardset_test3.words.new(name:"hair", meaning:"髪")
cardset_test3.words.new(name:"nose", meaning:"鼻")
cardset_test3.words.new(name:"mouth", meaning:"口")
cardset_test3.words.new(name:"tooth", meaning:"歯")
cardset_test3.words.new(name:"teeth", meaning:"toothの複数形")
cardset_test3.words.new(name:"arm", meaning:"腕")
cardset_test3.words.new(name:"knee", meaning:"膝")
cardset_test3.words.new(name:"elbow", meaning:"ひじ")
cardset_test3.words.new(name:"shoulder", meaning:"肩")
cardset_test3.words.new(name:"neck", meaning:"首")
cardset_test3.words.new(name:"cheek", meaning:"ほほ")
cardset_test3.words.new(name:"chin", meaning:"あご")
cardset_test3.words.new(name:"eyebrow", meaning:"眉毛")
cardset_test3.words.new(name:"eyelash", meaning:"まつげ")
cardset_test3.words.new(name:"ankle", meaning:"くるぶし")
cardset_test3.words.new(name:"toe", meaning:"つま先")
cardset_test3.words.new(name:"heel", meaning:"かかと")
cardset_test3.words.new(name:"hand", meaning:"手")
cardset_test3.words.new(name:"palm", meaning:"手のひら")
cardset_test3.words.new(name:"finger", meaning:"指")
cardset_test3.words.new(name:"foot", meaning:"足")
cardset_test3.words.new(name:"feet", meaning:"footの複数形")



cardset_test3.save


cardset_test4 = Cardset.new(name: "スポーツ", user_id: 1, use: 2)
cardset_test3.words.new(name:"soccer", meaning:"サッカー")
cardset_test3.words.new(name:"basketball", meaning:"バスケットボール")
cardset_test3.words.new(name:"baseball", meaning:"野球")
cardset_test3.words.new(name:"tennis", meaning:"テニス")
cardset_test3.words.new(name:"bat", meaning:"バット")
cardset_test3.words.new(name:"racket", meaning:"ラケット")
cardset_test3.words.new(name:"sports", meaning:"スポーツ")
cardset_test4.words.new(name:"table tennis", meaning:"話す")
cardset_test4.words.new(name:"swimming", meaning:"助ける")
cardset_test4.words.new(name:"track and field", meaning:"陸上")
cardset_test4.words.new(name:"ballet", meaning:"バレエ")
cardset_test4.words.new(name:"goal", meaning:"ゴール")
cardset_test4.words.new(name:"win", meaning:"勝つ")
cardset_test4.words.new(name:"lose", meaning:"負ける")
cardset_test4.words.new(name:"hit", meaning:"打つ")
cardset_test4.words.new(name:"throw", meaning:"投げる")
cardset_test4.words.new(name:"kick", meaning:"蹴る")
cardset_test4.words.new(name:"receive", meaning:"受ける")
cardset_test4.words.new(name:"get", meaning:"手に入れる")
cardset_test4.words.new(name:"return", meaning:"返す")
cardset_test4.words.new(name:"jump", meaning:"飛ぶ")
cardset_test4.words.new(name:"rest", meaning:"休み")

cardset_test4.save

cardset_test5 = Cardset.new(name: "食べ物", user_id: 1, use: 2)

cardset_test5.words.new(name:"food", meaning:"食べ物")
cardset_test5.words.new(name:"bread", meaning:"パン")
cardset_test5.words.new(name:"rice", meaning:"米")
cardset_test5.words.new(name:"egg", meaning:"卵")
cardset_test5.words.new(name:"cake", meaning:"ケーキ")
cardset_test5.words.new(name:"fruit", meaning:"果物")
cardset_test5.words.new(name:"apple", meaning:"りんご")
cardset_test5.words.new(name:"orange", meaning:"オレンジ")
cardset_test5.words.new(name:"lemon", meaning:"レモン")
cardset_test5.words.new(name:"milk", meaning:"ミルク")
cardset_test5.words.new(name:"melon", meaning:"メロン")
cardset_test5.words.new(name:"watermelon", meaning:"スイカ")
cardset_test5.words.new(name:"grape", meaning:"ぶどう")
cardset_test5.words.new(name:"tomato", meaning:"トマト")
cardset_test5.words.new(name:"potato", meaning:"ポテト")
cardset_test5.words.new(name:"carrot", meaning:"人参")
cardset_test5.words.new(name:"cabbage", meaning:"キャベツ")
cardset_test5.words.new(name:"letuce", meaning:"レタス")
cardset_test5.words.new(name:"onion", meaning:"オニオン")
cardset_test5.words.new(name:"garlic", meaning:"にんにく")
cardset_test5.words.new(name:"spinach", meaning:"ほうれん草")
cardset_test5.words.new(name:"radish", meaning:"かぶ")
cardset_test5.words.new(name:"fish", meaning:"魚")
cardset_test5.words.new(name:"tuna", meaning:"マグロ")
cardset_test5.words.new(name:"salmon", meaning:"さけ")
cardset_test5.words.new(name:"octopus", meaning:"たこ")
cardset_test5.words.new(name:"squid", meaning:"いか")
cardset_test5.words.new(name:"rice ball", meaning:"おにぎり")

cardset_test5.save


# cardset_test6 = Cardset.new(name: "テスト6", user_id: 1, use: 2)

# cardset_test6.words.new(name:"come", meaning:"来る")
# cardset_test6.words.new(name:"walk", meaning:"歩く")
# cardset_test6.words.new(name:"run", meaning:"走る")
# cardset_test6.words.new(name:"speak", meaning:"話す")
# cardset_test6.words.new(name:"say", meaning:"言う")
# cardset_test6.words.new(name:"talk", meaning:"話す")
# cardset_test6.words.new(name:"help", meaning:"助ける")
# cardset_test6.words.new(name:"have", meaning:"持っている")
# cardset_test6.words.new(name:"bring", meaning:"持ってくる")
# cardset_test6.words.new(name:"take", meaning:"持っていく")
# cardset_test6.words.new(name:"like", meaning:"好む")
# cardset_test6.words.new(name:"love", meaning:"愛する")
# cardset_test6.words.new(name:"call", meaning:"呼ぶ")
# cardset_test6.words.new(name:"succeed", meaning:"成功する")
# cardset_test6.words.new(name:"fail", meaning:"失敗する")
# cardset_test6.words.new(name:"lent", meaning:"貸す")
# cardset_test6.words.new(name:"check", meaning:"確認する")
# cardset_test6.words.new(name:"enter", meaning:"入る")
# cardset_test6.words.new(name:"fly", meaning:"飛ぶ")
# cardset_test6.words.new(name:"vanish", meaning:"消える")

# cardset_test6.save

# cardset_test7 = Cardset.new(name: "テスト7", user_id: 1, use: 2)

# cardset_test7.words.new(name:"come", meaning:"来る")
# cardset_test7.words.new(name:"walk", meaning:"歩く")
# cardset_test7.words.new(name:"run", meaning:"走る")
# cardset_test7.words.new(name:"speak", meaning:"話す")
# cardset_test7.words.new(name:"say", meaning:"言う")
# cardset_test7.words.new(name:"talk", meaning:"話す")
# cardset_test7.words.new(name:"help", meaning:"助ける")
# cardset_test7.words.new(name:"have", meaning:"持っている")
# cardset_test7.words.new(name:"bring", meaning:"持ってくる")
# cardset_test7.words.new(name:"take", meaning:"持っていく")
# cardset_test7.words.new(name:"like", meaning:"好む")
# cardset_test7.words.new(name:"love", meaning:"愛する")
# cardset_test7.words.new(name:"call", meaning:"呼ぶ")
# cardset_test7.words.new(name:"succeed", meaning:"成功する")
# cardset_test7.words.new(name:"fail", meaning:"失敗する")
# cardset_test7.words.new(name:"lent", meaning:"貸す")
# cardset_test7.words.new(name:"check", meaning:"確認する")
# cardset_test7.words.new(name:"enter", meaning:"入る")
# cardset_test7.words.new(name:"fly", meaning:"飛ぶ")
# cardset_test7.words.new(name:"vanish", meaning:"消える")

# cardset_test7.save


# cardset_test8 = Cardset.new(name: "テスト8", user_id: 1, use: 2)

# cardset_test8.words.new(name:"come", meaning:"来る")
# cardset_test8.words.new(name:"walk", meaning:"歩く")
# cardset_test8.words.new(name:"run", meaning:"走る")
# cardset_test8.words.new(name:"speak", meaning:"話す")
# cardset_test8.words.new(name:"say", meaning:"言う")
# cardset_test8.words.new(name:"talk", meaning:"話す")
# cardset_test8.words.new(name:"help", meaning:"助ける")
# cardset_test8.words.new(name:"have", meaning:"持っている")
# cardset_test8.words.new(name:"bring", meaning:"持ってくる")
# cardset_test8.words.new(name:"take", meaning:"持っていく")
# cardset_test8.words.new(name:"like", meaning:"好む")
# cardset_test8.words.new(name:"love", meaning:"愛する")
# cardset_test8.words.new(name:"call", meaning:"呼ぶ")
# cardset_test8.words.new(name:"succeed", meaning:"成功する")
# cardset_test8.words.new(name:"fail", meaning:"失敗する")
# cardset_test8.words.new(name:"lent", meaning:"貸す")
# cardset_test8.words.new(name:"check", meaning:"確認する")
# cardset_test8.words.new(name:"enter", meaning:"入る")
# cardset_test8.words.new(name:"fly", meaning:"飛ぶ")
# cardset_test8.words.new(name:"vanish", meaning:"消える")

# cardset_test8.save