

# cardset = Cardset.new(name: "デフォルトセット１", user_id: 1)

# cardset.words.new(name:"come", meaning:"来る")
# cardset.words.new(name:"walk", meaning:"歩く")
# cardset.words.new(name:"run", meaning:"走る")
# cardset.words.new(name:"speak", meaning:"話す")
# cardset.words.new(name:"say", meaning:"言う")
# cardset.words.new(name:"talk", meaning:"話す")
# cardset.words.new(name:"help", meaning:"助ける")
# cardset.words.new(name:"have", meaning:"持っている")
# cardset.words.new(name:"bring", meaning:"持ってくる")
# cardset.words.new(name:"take", meaning:"持っていく")
# cardset.words.new(name:"like", meaning:"好む")
# cardset.words.new(name:"love", meaning:"愛する")
# cardset.words.new(name:"call", meaning:"呼ぶ")
# cardset.words.new(name:"succeed", meaning:"成功する")
# cardset.words.new(name:"fail", meaning:"失敗する")
# cardset.words.new(name:"lent", meaning:"貸す")
# cardset.words.new(name:"check", meaning:"確認する")
# cardset.words.new(name:"enter", meaning:"入る")
# cardset.words.new(name:"fly", meaning:"飛ぶ")
# cardset.words.new(name:"vanish", meaning:"消える")

# cardset.save


cardset_test1 = Cardset.new(name: "テスト１", user_id: 1, use: 2)

cardset_test1.words.new(name:"come", meaning:"来る")
cardset_test1.words.new(name:"walk", meaning:"歩く")
cardset_test1.words.new(name:"run", meaning:"走る")
cardset_test1.words.new(name:"speak", meaning:"話す")
cardset_test1.words.new(name:"say", meaning:"言う")
cardset_test1.words.new(name:"talk", meaning:"話す")
cardset_test1.words.new(name:"help", meaning:"助ける")
cardset_test1.words.new(name:"have", meaning:"持っている")
cardset_test1.words.new(name:"bring", meaning:"持ってくる")
cardset_test1.words.new(name:"take", meaning:"持っていく")
cardset_test1.words.new(name:"like", meaning:"好む")
cardset_test1.words.new(name:"love", meaning:"愛する")
cardset_test1.words.new(name:"call", meaning:"呼ぶ")
cardset_test1.words.new(name:"succeed", meaning:"成功する")
cardset_test1.words.new(name:"fail", meaning:"失敗する")
cardset_test1.words.new(name:"lent", meaning:"貸す")
cardset_test1.words.new(name:"check", meaning:"確認する")
cardset_test1.words.new(name:"enter", meaning:"入る")
cardset_test1.words.new(name:"fly", meaning:"飛ぶ")
cardset_test1.words.new(name:"vanish", meaning:"消える")

cardset_test1.save


cardset_test2 = Cardset.new(name: "テスト2", user_id: 1, use: 2)

cardset_test2.words.new(name:"come", meaning:"来る")
cardset_test2.words.new(name:"walk", meaning:"歩く")
cardset_test2.words.new(name:"run", meaning:"走る")
cardset_test2.words.new(name:"speak", meaning:"話す")
cardset_test2.words.new(name:"say", meaning:"言う")
cardset_test2.words.new(name:"talk", meaning:"話す")
cardset_test2.words.new(name:"help", meaning:"助ける")
cardset_test2.words.new(name:"have", meaning:"持っている")
cardset_test2.words.new(name:"bring", meaning:"持ってくる")
cardset_test2.words.new(name:"take", meaning:"持っていく")
cardset_test2.words.new(name:"like", meaning:"好む")
cardset_test2.words.new(name:"love", meaning:"愛する")
cardset_test2.words.new(name:"call", meaning:"呼ぶ")
cardset_test2.words.new(name:"succeed", meaning:"成功する")
cardset_test2.words.new(name:"fail", meaning:"失敗する")
cardset_test2.words.new(name:"lent", meaning:"貸す")
cardset_test2.words.new(name:"check", meaning:"確認する")
cardset_test2.words.new(name:"enter", meaning:"入る")
cardset_test2.words.new(name:"fly", meaning:"飛ぶ")
cardset_test2.words.new(name:"vanish", meaning:"消える")

cardset_test2.save

cardset_test3 = Cardset.new(name: "テスト3", user_id: 1, use: 2)

cardset_test3.words.new(name:"come", meaning:"来る")
cardset_test3.words.new(name:"walk", meaning:"歩く")
cardset_test3.words.new(name:"run", meaning:"走る")
cardset_test3.words.new(name:"speak", meaning:"話す")
cardset_test3.words.new(name:"say", meaning:"言う")
cardset_test3.words.new(name:"talk", meaning:"話す")
cardset_test3.words.new(name:"help", meaning:"助ける")
cardset_test3.words.new(name:"have", meaning:"持っている")
cardset_test3.words.new(name:"bring", meaning:"持ってくる")
cardset_test3.words.new(name:"take", meaning:"持っていく")
cardset_test3.words.new(name:"like", meaning:"好む")
cardset_test3.words.new(name:"love", meaning:"愛する")
cardset_test3.words.new(name:"call", meaning:"呼ぶ")
cardset_test3.words.new(name:"succeed", meaning:"成功する")
cardset_test3.words.new(name:"fail", meaning:"失敗する")
cardset_test3.words.new(name:"lent", meaning:"貸す")
cardset_test3.words.new(name:"check", meaning:"確認する")
cardset_test3.words.new(name:"enter", meaning:"入る")
cardset_test3.words.new(name:"fly", meaning:"飛ぶ")
cardset_test3.words.new(name:"vanish", meaning:"消える")

cardset_test3.save


cardset_test4 = Cardset.new(name: "テスト4", user_id: 1, use: 2)

cardset_test4.words.new(name:"come", meaning:"来る")
cardset_test4.words.new(name:"walk", meaning:"歩く")
cardset_test4.words.new(name:"run", meaning:"走る")
cardset_test4.words.new(name:"speak", meaning:"話す")
cardset_test4.words.new(name:"say", meaning:"言う")
cardset_test4.words.new(name:"talk", meaning:"話す")
cardset_test4.words.new(name:"help", meaning:"助ける")
cardset_test4.words.new(name:"have", meaning:"持っている")
cardset_test4.words.new(name:"bring", meaning:"持ってくる")
cardset_test4.words.new(name:"take", meaning:"持っていく")
cardset_test4.words.new(name:"like", meaning:"好む")
cardset_test4.words.new(name:"love", meaning:"愛する")
cardset_test4.words.new(name:"call", meaning:"呼ぶ")
cardset_test4.words.new(name:"succeed", meaning:"成功する")
cardset_test4.words.new(name:"fail", meaning:"失敗する")
cardset_test4.words.new(name:"lent", meaning:"貸す")
cardset_test4.words.new(name:"check", meaning:"確認する")
cardset_test4.words.new(name:"enter", meaning:"入る")
cardset_test4.words.new(name:"fly", meaning:"飛ぶ")
cardset_test4.words.new(name:"vanish", meaning:"消える")

cardset_test4.save

cardset_test5 = Cardset.new(name: "テスト5", user_id: 1, use: 2)

cardset_test5.words.new(name:"come", meaning:"来る")
cardset_test5.words.new(name:"walk", meaning:"歩く")
cardset_test5.words.new(name:"run", meaning:"走る")
cardset_test5.words.new(name:"speak", meaning:"話す")
cardset_test5.words.new(name:"say", meaning:"言う")
cardset_test5.words.new(name:"talk", meaning:"話す")
cardset_test5.words.new(name:"help", meaning:"助ける")
cardset_test5.words.new(name:"have", meaning:"持っている")
cardset_test5.words.new(name:"bring", meaning:"持ってくる")
cardset_test5.words.new(name:"take", meaning:"持っていく")
cardset_test5.words.new(name:"like", meaning:"好む")
cardset_test5.words.new(name:"love", meaning:"愛する")
cardset_test5.words.new(name:"call", meaning:"呼ぶ")
cardset_test5.words.new(name:"succeed", meaning:"成功する")
cardset_test5.words.new(name:"fail", meaning:"失敗する")
cardset_test5.words.new(name:"lent", meaning:"貸す")
cardset_test5.words.new(name:"check", meaning:"確認する")
cardset_test5.words.new(name:"enter", meaning:"入る")
cardset_test5.words.new(name:"fly", meaning:"飛ぶ")
cardset_test5.words.new(name:"vanish", meaning:"消える")

cardset_test5.save


cardset_test6 = Cardset.new(name: "テスト6", user_id: 1, use: 2)

cardset_test6.words.new(name:"come", meaning:"来る")
cardset_test6.words.new(name:"walk", meaning:"歩く")
cardset_test6.words.new(name:"run", meaning:"走る")
cardset_test6.words.new(name:"speak", meaning:"話す")
cardset_test6.words.new(name:"say", meaning:"言う")
cardset_test6.words.new(name:"talk", meaning:"話す")
cardset_test6.words.new(name:"help", meaning:"助ける")
cardset_test6.words.new(name:"have", meaning:"持っている")
cardset_test6.words.new(name:"bring", meaning:"持ってくる")
cardset_test6.words.new(name:"take", meaning:"持っていく")
cardset_test6.words.new(name:"like", meaning:"好む")
cardset_test6.words.new(name:"love", meaning:"愛する")
cardset_test6.words.new(name:"call", meaning:"呼ぶ")
cardset_test6.words.new(name:"succeed", meaning:"成功する")
cardset_test6.words.new(name:"fail", meaning:"失敗する")
cardset_test6.words.new(name:"lent", meaning:"貸す")
cardset_test6.words.new(name:"check", meaning:"確認する")
cardset_test6.words.new(name:"enter", meaning:"入る")
cardset_test6.words.new(name:"fly", meaning:"飛ぶ")
cardset_test6.words.new(name:"vanish", meaning:"消える")

cardset_test6.save

cardset_test7 = Cardset.new(name: "テスト7", user_id: 1, use: 2)

cardset_test7.words.new(name:"come", meaning:"来る")
cardset_test7.words.new(name:"walk", meaning:"歩く")
cardset_test7.words.new(name:"run", meaning:"走る")
cardset_test7.words.new(name:"speak", meaning:"話す")
cardset_test7.words.new(name:"say", meaning:"言う")
cardset_test7.words.new(name:"talk", meaning:"話す")
cardset_test7.words.new(name:"help", meaning:"助ける")
cardset_test7.words.new(name:"have", meaning:"持っている")
cardset_test7.words.new(name:"bring", meaning:"持ってくる")
cardset_test7.words.new(name:"take", meaning:"持っていく")
cardset_test7.words.new(name:"like", meaning:"好む")
cardset_test7.words.new(name:"love", meaning:"愛する")
cardset_test7.words.new(name:"call", meaning:"呼ぶ")
cardset_test7.words.new(name:"succeed", meaning:"成功する")
cardset_test7.words.new(name:"fail", meaning:"失敗する")
cardset_test7.words.new(name:"lent", meaning:"貸す")
cardset_test7.words.new(name:"check", meaning:"確認する")
cardset_test7.words.new(name:"enter", meaning:"入る")
cardset_test7.words.new(name:"fly", meaning:"飛ぶ")
cardset_test7.words.new(name:"vanish", meaning:"消える")

cardset_test7.save


cardset_test8 = Cardset.new(name: "テスト8", user_id: 1, use: 2)

cardset_test8.words.new(name:"come", meaning:"来る")
cardset_test8.words.new(name:"walk", meaning:"歩く")
cardset_test8.words.new(name:"run", meaning:"走る")
cardset_test8.words.new(name:"speak", meaning:"話す")
cardset_test8.words.new(name:"say", meaning:"言う")
cardset_test8.words.new(name:"talk", meaning:"話す")
cardset_test8.words.new(name:"help", meaning:"助ける")
cardset_test8.words.new(name:"have", meaning:"持っている")
cardset_test8.words.new(name:"bring", meaning:"持ってくる")
cardset_test8.words.new(name:"take", meaning:"持っていく")
cardset_test8.words.new(name:"like", meaning:"好む")
cardset_test8.words.new(name:"love", meaning:"愛する")
cardset_test8.words.new(name:"call", meaning:"呼ぶ")
cardset_test8.words.new(name:"succeed", meaning:"成功する")
cardset_test8.words.new(name:"fail", meaning:"失敗する")
cardset_test8.words.new(name:"lent", meaning:"貸す")
cardset_test8.words.new(name:"check", meaning:"確認する")
cardset_test8.words.new(name:"enter", meaning:"入る")
cardset_test8.words.new(name:"fly", meaning:"飛ぶ")
cardset_test8.words.new(name:"vanish", meaning:"消える")

cardset_test8.save